# Kubernetes Infrastructure Release
#
# This pipeline's scope is to validate and deploy infrastructural
# changes to the microservice environments with kubernetes. This includes:
#
# * a stage to publish ARM templates and tests
# * a stage to deploy and validate the functional working of the
#   deployed infrastructure in an integration environment
# * the execution of tests scoped to custom roles in the AAD tenant
# * the deployment to the microservice environments
#   * dev
#   * int
#   * prod
#
# This pipeline is automatically triggered on any change in the arm-templates
# folder containing this ADO pipeline definition and infra-as-code.

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure-k8-service/infrastructure/arm-templates/*
    - azure-k8-service/infrastructure/deploy-infra/arm/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - azure-k8-service/infrastructure/arm-templates/*
    - azure-k8-service/infrastructure/deploy-infra/arm/*

# loading all variables groups once, to resolve Azure DevOps problems with resolving variables
variables:
- group: k8-vg-dev
# - group: k8-vg-int
# - group: k8-vg-prd

stages:
# Validate and publish dependencies for downstream stages
- stage: Build
  displayName: 'IaC Build'
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Deployment scripts to: $(Build.ArtifactStagingDirectory)'
      inputs:
        sourceFolder: 'azure-k8-service/infrastructure/deployment-scripts'
        targetFolder: '$(Build.ArtifactStagingDirectory)/scripts'
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        sourceFolder: 'azure-k8-service/infrastructure/arm-templates'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Pipeline.Workspace)'
      artifact: IaCAndTests

# Deploy Dev 
- stage: DeployDevInfra
  displayName: 'Deploy: DEV'
  dependsOn: build
  variables:
  - group: k8-vg-dev
  - name: armArtifactName
    value: IaCAndTests

  jobs:
  - template: ado-template-k8env.yml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'k8-env-dev'
