apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: k8s.gcr.io/container1
    name: container1
    volumeMounts:
    - mountPath: /shared
      name: shared-scratch-space
  - image: k8s.gcr.io/container2
    name: container2
    volumeMounts:
    - mountPath: /shared
      name: shared-scratch-space
  volumes:
  - name: shared-scratch-space
    emptyDir: {}
