# Set of steps to attach datastores from a config file to a ML workspace
steps:
- script: | 
    sleep 1m
  displayName: "Wait for a short time to let the ML Workspace MSI Propagate"

- task: AzureCLI@1
  displayName: 'Get current SP'
  inputs:
    azureSubscription: $(serviceConnection)
    scriptLocation: inlineScript
    inlineScript: |
      spn=$(az account show  --query "user.name" -o tsv)
      az keyvault set-policy -n aksbp-kv-$(environment) --spn $spn --secret-permissions get list  
                    

- task: AzureCLI@1
  displayName: 'Attach datastores from datastore config file'
  inputs:
    azureSubscription: $(serviceConnection)
    scriptLocation: inlineScript
    inlineScript: |
      subscription=$(az account list --query "[?isDefault].id | [0]" --output tsv)
      sh $(Pipeline.Workspace)/$(armArtifactName)/scripts/attachDatastores.sh $(Pipeline.Workspace) $(armArtifactName) $(workspaceName) $subscription $(environment)
