# Template pipeline for the deployment of shared infrastructure
# that the ML workspaces depend on.
#
# This pipeline deploys a KeyVault instance, Two Storage accounts (one
# for the ML workspace logs, one as a shared data store), two Container
# Registries (one staging, one ML workspace-related) and an Application
# Insights instance. Storage accounts are preconfigured with a set of blob
# containers (initialization, metrics, datasets, ..)

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: azure-k8-service/infrastructure/deployment-scripts/check-keyvault.sh
      arguments: '$(BASE_NAME) $(ENV)'
      useGlobalConfig: true
      workingDirectory: $(Pipeline.Workspace)/$(armArtifactName)/scripts

# - task: AzureResourceGroupDeployment@2
#   displayName: 'Deployment: Container Registry'
#   inputs:
#     azureSubscription: $(AZURE_RM_SVC_CONNECTION)
#     resourceGroupName: $(BASE_NAME)-rg-$(ENV)
#     location: $(location)
#     csmFile: '$(Pipeline.Workspace)/$(armArtifactName)/container-registry/template.json'
#     csmParametersFile: '$(Pipeline.Workspace)/$(armArtifactName)/container-registry/parameters.$(ENV).json'
#     deploymentMode: $(deploymentMode)

