# Template pipeline for the AKS Environment Deployment
# This includes shared infrastructure and n AKS workspaces, compute and
# their configuration.
# 
#
# :param environment: the environment for deployment e.g. dev

jobs:
  - deployment: ValidateSharedInfra
    variables:
    - group: k8-vg-dev
    - name: RESOURCE_GROUP_NAME
      value: $(BASE_NAME)-rg-$(ENV)
    - name: deploymentMode
      value: 'Validation'
    pool:
      vmImage: '${{ parameters.vmImage }}'
    environment: '${{ parameters.environment }}'
    strategy:
      runOnce:
        deploy:
          steps:
          # - task: AzureCLI@1
          #   displayName: 'Deployment: Resource Group'
          #   inputs:
          #     azureSubscription: $(AZURE_RM_SVC_CONNECTION)
          #     scriptLocation: 'inlineScript'
          #     inlineScript: |
          #                   az group create -n $(RESOURCE_GROUP_NAME) \
          #                   -l $(LOCATION)
          # - task:
            - template: ado-template-k8env-sharedinfra.yml



  - deployment: DeploySharedInfra
    dependsOn: ValidateSharedInfra
    variables:
    - group: k8-vg-dev
    - name: RESOURCE_GROUP_NAME
      value: $(BASE_NAME)-rg-$(ENV)
    - name: deploymentMode
      value: 'Incremental'
    pool:
      vmImage: '${{ parameters.vmImage }}'
    environment: '${{ parameters.environment }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ado-template-k8env-sharedinfra.yml