# Template pipeline for the deployment of shared infrastructure
# that the ML workspaces depend on.
#
# This pipeline deploys a KeyVault instance, Two Storage accounts (one
# for the ML workspace logs, one as a shared data store), two Container
# Registries (one staging, one ML workspace-related) and an Application
# Insights instance. Storage accounts are preconfigured with a set of blob
# containers (initialization, metrics, datasets, ..)

steps:
  - task: AzureCLI@2
    displayName: Check if KeyVault exists
    condition: ne(variables['deploymentMode'], 'Validation')
    inputs:
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: azure-k8-service/infrastructure/deployment-scripts/check-keyvault.sh
      arguments: '$(BASE_NAME) $(ENV)'
      useGlobalConfig: true
      workingDirectory: $(Pipeline.Workspace)/$(armArtifactName)/scripts
  
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'kubernetes-infra-release'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'ls $(Pipeline.Workspace)/$(armArtifactName)/arm-templates/keyvault/'

  # - task: AzureResourceManagerTemplateDeployment@3
  #   inputs:
  #     deploymentScope: 'Resource Group'
  #     azureResourceManagerConnection: $(AZURE_RM_SVC_CONNECTION)
  #     action: 'Create Or Update Resource Group'
  #     resourceGroupName: $(RESOURCE_GROUP_NAME)
  #     location: $(LOCATION)
  #     templateLocation: 'Linked artifact'
  #     csmFile: '$(Pipeline.Workspace)/$(armArtifactName)/arm-templates/keyvault/template.json'
  #     csmParametersFile: '$(Pipeline.Workspace)/$(armArtifactName)/arm-templates/keyvault/parameters.$(ENV).json'
  #     deploymentMode: $(deploymentMode)
  #     overrideParameters: -name "$(BASE_NAME)-kv-$(ENV)" -objectId $(SP_OBJ_ID) -createMode $(createMode)
  #     deploymentName: 'KeyvaultDeployment'