# Template pipeline for the deployment of shared infrastructure
# that the ML workspaces depend on.
#
# This pipeline deploys a KeyVault instance, Two Storage accounts (one
# for the ML workspace logs, one as a shared data store), two Container
# Registries (one staging, one ML workspace-related) and an Application
# Insights instance. Storage accounts are preconfigured with a set of blob
# containers (initialization, metrics, datasets, ..)

steps:
  # - task: AzureCLI@1
  #   displayName: Check if KeyVault exists & deploy
  #   condition: ne(variables['deploymentMode'], 'Validation')
  #   inputs:
  #     azureSubscription: $(AZURE_RM_SVC_CONNECTION)
  #     scriptLocation: inlineScript
  #     workingDirectory: $(Pipeline.Workspace)/$(armArtifactName)/scripts
  #     inlineScript: 'sudo sh check.sh'
  # - script: |
  #           Add other tasks to build, test, and deploy your project.
  #           echo See https://aka.ms/yaml
  #   displayName: 'Run a multi-line script'
  - task: AzureCLI@2
    displayName: Check if KeyVault
    inputs:
      azureSubscription: 'kubernetes-infra-release'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      arguments: 'a b'
      workingDirectory: $(Pipeline.Workspace)/$(armArtifactName)/scripts
      inlineScript: |
                    sh check.sh

# - task: AzureResourceGroupDeployment@2
#   displayName: 'Deployment: Container Registry'
#   inputs:
#     azureSubscription: $(AZURE_RM_SVC_CONNECTION)
#     resourceGroupName: $(BASE_NAME)-rg-$(ENV)
#     location: $(location)
#     csmFile: '$(Pipeline.Workspace)/$(armArtifactName)/container-registry/template.json'
#     csmParametersFile: '$(Pipeline.Workspace)/$(armArtifactName)/container-registry/parameters.$(ENV).json'
#     deploymentMode: $(deploymentMode)

