# Kubernetes Infrastructure Release
#
# This pipeline's scope is to validate and deploy infrastructural
# changes to the microservice environments with kubernetes. This includes:
#
# * a stage to publish ARM templates and tests
# * a stage to deploy and validate the functional working of the
#   deployed infrastructure in an integration environment
# * the execution of tests scoped to custom roles in the AAD tenant
# * the deployment to the microservice environments
#   * dev
#   * int
#   * prod
#
# This pipeline is automatically triggered on any change in the arm-templates
# folder containing this ADO pipeline definition and infra-as-code.

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure-k8-service/infrastructure/arm-templates/*
    - azure-k8-service/infrastructure/deploy_infra/arm/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - azure-k8-service/infrastructure/arm-templates/*
    - azure-k8-service/infrastructure/deploy_infra/arm/*

pool:
  vmImage: 'ubuntu-latest'

# loading all variables groups once, to resolve Azure DevOps problems with resolving variables
variables:
- group: k8-vg-dev
# - group: k8-vg-int
# - group: k8-vg-prd

stages:
# Validate and publish dependencies for downstream stages
- stage: Build
  displayName: 'IaC Build'
  jobs:
  - job: Build
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Deployment scripts'
      inputs:
        sourceFolder: 'azure-k8-service/infrastructure/deployment-scripts'
        targetFolder: '$(Build.ArtifactStagingDirectory)/scripts'
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        sourceFolder: 'azure-k8-service/infrastructure/arm-templates'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: IaCAndTests

# Deploy Dev 
- stage: DeployDevInfra
  displayName: 'Deploy: DEV'
  dependsOn: build
  variables:
  - group: k8-vg-dev
  - name: armArtifactName
    value: IaCAndTests

  jobs:
  - template: ado-template-k8env.yml
    parameters:
      vmImage: 'ubuntu-latest'
      environment: 'dev'

# # Deploy Integration Environment, Run Post-Deployment Tests
# - stage: DeployIntInfra
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   displayName: 'Deploy: INT'
#   variables:
#   - group: aksbp-int
#   - name: armArtifactName
#     value: IaCAndTests
#     # value: aksbp-infra-validated
#   - name: sharedTemplatesPipelineDefinitionId
#     value: 4531
#   - name: sharedTemplatesArtifactName
#     value: ATIIT4AD_SHARED_TEMPLATES
#   - name: resource_group_name
#     value: aksbp-aml-int

#   jobs:
#   - template: ado-template-mlenv.yml
#     parameters:
#       environment: 'aksbp-aml-int'
#       agentpool: 'Athena-CPU-Deep-int'
#       workspaces:
#       - integration
#       - tl
#       - ts
#       - vru
#       - unittests
#       - lidar
#       - cv2
#       - cv1
#       - monitoring
#       - radar
#       - blockage

# Run Custom Role Tests
# After having run these tests, we publish the infrastructure
# templates as new artifacts 'aksbp-infra-validated'. These artifacts
# are then used for the INT and PROD environment deployments.
# Commented since we do not have the model developer role as service connection in ADO today
# - stage: CustomRoleValidation
#   displayName: 'Test Custom Roles'
#   variables:
#   - group: aksbp-int
#   - name: armArtifactName
#     value: IaCAndTests
#   - name: workspaceName
#     value: aksbp-integration-aml #-{env}
#   - name: containerRegistryInstance
#     value: aksbpacrint

#   jobs:
#   - job: CNNRoleTest
#     pool:
#       name: 'Athena-CPU-Deep-int'
#     steps:
#     - download: current
#       artifact: $(armArtifactName)
#     - template: ado-template-mlenv-tests.yml
#       parameters:
#         report_name: 'model_developer'
#         spc: 'aksbp-poc-dev-model-developer-role'
#     # Publish Validated Artifacts for Environment Deployments
#     - publish: '$(Pipeline.Workspace)/$(armArtifactName)'
#       artifact: aksbp-infra-validated
#       condition: succeeded()
#       displayName: 'Published Validated Artifacts (ARM + Tests)'

# # Deploy Prd Environment, Run Post-Deployment Tests
# - stage: DeployPrdInfra
#   displayName: 'Deploy: PRD'
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   variables:
#   - group: aksbp-prd
#   - name: armArtifactName
#     value: IaCAndTests
#     # value: aksbp-infra-validated
#   - name: sharedTemplatesPipelineDefinitionId
#     value: 4531
#   - name: sharedTemplatesArtifactName
#     value: ATIIT4AD_SHARED_TEMPLATES
#   - name: resource_group_name
#     value: aksbp-aml-prd

#   jobs:
#   - template: ado-template-mlenv.yml
#     parameters:
#       environment: 'aksbp-aml-prd'
#       agentpool: 'Athena-CPU-Deep-prd'
#       workspaces:
#       - tl
#       - ts
#       - vru
#       - unittests
#       - lidar
#       - cv2
#       - cv1
#       - radar
#       - blockage
