apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-openapi
spec:
  type: LoadBalancer
  selector:
    app: openapi
  ports:
    - protocol: TCP
      port: 5000 # 'public' port...
      targetPort: 5001 # 'internal' port...