# Kubernetes Infrastructure Release
#
# This pipeline's scope is to validate and deploy infrastructural
# changes to the K8s environments. This includes:
#
# * a stage to publish TF templates and tests
# * a stage to deploy and validate the functional working of the
#   deployed infrastructure in an integration environment
#
# This pipeline is automatically triggered on any change in the tf-templates
# folder containing this ADO pipeline definition and infra-as-code.

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/tf-templates/*
    - infrastructure/deploy-infra-terraform/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/tf-templates/*
    - infrastructure/deploy-infra-terraform/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: mlops-vg-dev
- name: RESOURCE_GROUP_NAME
  value: $(BASE_NAME)-rg-$(ENV)
- name: WORKSPACE_NAME
  value: $(BASE_NAME)-aml-$(ENV)



steps:
- task: AzureCLI@1
  displayName: 'Deployment: Resource Group'
  inputs:
    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
    scriptLocation: 'inlineScript'
    inlineScript: |
                  az group create -n $(RESOURCE_GROUP_NAME) \
                  -l $(LOCATION)