# Template pipeline for the AKS Environment Deployment
# This includes shared infrastructure and n AKS workspaces, compute and
# their configuration.
# 
#
# :param environment: the environment for deployment e.g. dev

jobs:
  - job:
  - deployment: ResourceGroupDeployment
    pool:
      vmImage: '${( parameters.vmImage )}'
    environment: 'dev'
    variables:
      - group: k8-vg-dev
      - name: RESOURCE_GROUP_NAME
        value: $(BASE_NAME)-rg-$(ENV)
      - name: STORAGE_NAME
        value: $(BASE_NAME)storage$(ENV)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@1
            displayName: 'Deployment: Resource Group'
            inputs:
              azureSubscription: $(AZURE_RM_SVC_CONNECTION)
              scriptLocation: 'inlineScript'
              inlineScript: |
                            az group create -n $(RESOURCE_GROUP_NAME) \
                            -l $(LOCATION)
          - task: AzureCLI@1
            displayName: 'Deployment: Storage'
            inputs:
              azureSubscription: $(AZURE_RM_SVC_CONNECTION)
              scriptLocation: 'inlineScript'
              inlineScript: |
                            az storage account create -n $(STORAGE_NAME) -g $(RESOURCE_GROUP_NAME) -l $(LOCATION)
          - task: AzureCLI@1
            displayName: 'Deployment: tfstate container'
            inputs:
              azureSubscription: $(AZURE_RM_SVC_CONNECTION)
              scriptLocation: 'inlineScript'
              inlineScript: |
                            az storage container create -n tfstate --account-name $(STORAGE_NAME)

          - task: AzureCLI@1
            displayName: Check if KeyVault exists
            condition: ne(variables['deploymentMode'], 'Validation')
            inputs:
              azureSubscription: $(AZURE_RM_SVC_CONNECTION)
              scriptLocation: inlineScript
              workingDirectory: $(Pipeline.Workspace)/$(armArtifactName)/scripts
              inlineScript: 'sh check-keyvault.sh $(BASE_NAME) $(ENV) $(RESOURCE_GROUP_NAME)'