

steps:
- task: AzureCLI@1
  displayName: 'Deployment: Resource Group'
  inputs:
    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
    scriptLocation: 'inlineScript'
    inlineScript: |
                  az group create -n $(RESOURCE_GROUP_NAME) \
                  -l $(LOCATION)